mysite/bikeshop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('bike_list/', views.BikeListView.as_view(), name='bike_list'),
    path('<int:pk>/', views.BikeDetailView.as_view(), name='bike_detail'),
    path('categories/', views.CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
    path('brands/', views.BrandListView.as_view(), name='brand_list'),
    path('brands/<int:pk>/', views.BrandDetailView.as_view(), name='brand_detail'),
    path('order/create/', views.OrderCreateView.as_view(), name='order_create'),
    path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('order/<int:pk>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('order/<int:pk>/create/', views.OrderUpdateView.as_view(), name='order_update'),
    path('order/<int:pk>/delete/', views.OrderDeleteView.as_view(), name='order_delete'),
    path('search/', views.search, name='search'),
    path('profilis/', views.profilis, name='profilis'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('bikeshop/', include('bikeshop.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='bikeshop/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/bikeshop/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from PIL import Image
from django.conf import settings


class Bike(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(upload_to='bikes', null=True, blank=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT)
    brand = models.ForeignKey('Brand', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    quantity_available = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='brands', null=True, blank=True)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='brands', null=True, blank=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS_CHOICES = (
        ('Pending', 'Pending'),
        ('Out for delivery', 'Out for delivery'),
        ('Delivered', 'Delivered')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bike = models.ForeignKey(Bike, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')
    quantity = models.IntegerField(default=1)
    shipping_address = models.CharField(max_length=200)
    billing_address = models.CharField(max_length=200)

    @property
    def total_price(self):
        return self.bike.price * self.quantity

    def __str__(self):
        return f"{self.user.username} - {self.bike.name}"



class Comment(models.Model):
    bike = models.ForeignKey('Bike', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Comment #{self.pk}'


class Profilis(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profilis')
    nuotrauka = models.ImageField(default='profile_pics/default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} profilis'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.nuotrauka.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.nuotrauka.path)


# extend the User model
User.profilis = property(lambda u: Profilis.objects.get_or_create(user=u)[0])

mysite/bikeshop/forms.py
from django import forms
from .models import Bike, Order, Comment, User, Profilis


class BikeForm(forms.ModelForm):
    class Meta:
        model = Bike
        fields = ['name', 'category', 'brand', 'description', 'price', 'image']


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['bike', 'quantity', 'shipping_address', 'billing_address']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']


class UserUpdateForm(forms.ModelForm):
    # email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfilisUpdateForm(forms.ModelForm):
    class Meta:
        model = Profilis
        fields = ['nuotrauka']

mysite/bikeshop/views.py
from django.shortcuts import render, redirect, reverse
from django.views import generic
from django.db.models import Q
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages
from django.views.generic.edit import FormMixin
from .models import Bike, Category, Brand, Order
from .forms import OrderForm, CommentForm, UserUpdateForm, ProfilisUpdateForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count
from django.contrib.auth.models import User
from django.views.generic import TemplateView


def index(request):
    brandu_kiekis = Brand.objects.count()
    modeliu_kiekis = Bike.objects.count()
    atliktu_uzsakymu_kiekis = Order.objects.filter(status__exact='Pending').count()
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    kontekstas = {
        'brandu_kiekis': brandu_kiekis,
        'modeliu_kiekis': modeliu_kiekis,
        'atliktu_uzsakymu_kiekis': atliktu_uzsakymu_kiekis,
        'num_visits': num_visits,
    }
    return render(request, 'index.html', context=kontekstas)




@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
                    messages.info(request, f'Vartotojas {username} užregistruotas!')
                    return redirect('login')
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    return render(request, 'register.html')


class BikeListView(generic.ListView):
    model = Bike
    template_name = 'bike_list.html'
    paginate_by = 6
    context_object_name = 'bikes'


class BikeDetailView(FormMixin, generic.DetailView):
    model = Bike
    template_name = 'bike_detail.html'
    context_object_name = 'bike'
    form_class = CommentForm

    def get_success_url(self):
        return reverse('bike_detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = self.get_form()
        return context


class OrderListView(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    model = Order
    template_name = 'order_list.html'
    context_object_name = 'orders'
    ordering = ['-date_ordered']

    def test_func(self):
        return self.request.user.is_authenticated

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user)


class CategoryListView(generic.ListView):
    model = Category
    template_name = 'category_list.html'
    context_object_name = 'categories'
    queryset = model.objects.annotate(num_bikes=Count('bike'))


class CategoryDetailView(FormMixin, generic.DetailView):
    model = Category
    template_name = 'category_detail.html'
    context_object_name = 'category'
    form_class = CommentForm


class BrandListView(generic.ListView):
    model = Brand
    template_name = 'brand_list.html'
    context_object_name = 'brands'
    queryset = model.objects.annotate(num_bikes=Count('bike'))


class BrandDetailView(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    model = Brand
    template_name = 'brand_detail.html'
    context_object_name = 'brand'

    def test_func(self):
        return self.request.user.is_authenticated


class OrderCreateView(LoginRequiredMixin, generic.CreateView):
    model = Order
    template_name = 'order_create.html'
    form_class = OrderForm
    success_url = '/bikeshop/orders/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.status = 'pending'
        messages.success(self.request, 'Your order has been created!')
        return super().form_valid(form)


class OrderDetailView(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    model = Order
    template_name = 'order_detail.html'
    context_object_name = 'order'

    def test_func(self):
        return self.request.user.is_authenticated


class OrderUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Order
    template_name = 'order_update.html'
    form_class = OrderForm
    context_object_name = 'order'
    success_url = '/bikeshop/orders/'

    def form_valid(self, form):
        messages.success(self.request, 'Your order has been updated!')
        return super().form_valid(form)

    def test_func(self):
        return self.request.user.is_authenticated


class OrderDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Order
    template_name = 'order_delete.html'
    context_object_name = 'order'

    def get_success_url(self):
        messages.success(self.request, 'Your order has been deleted.')
        return reverse('order_list')

    def test_func(self):
        return self.request.user.is_authenticated


def search(request):
    query = request.GET.get('query')
    search_results = Bike.objects.filter(
        Q(name__icontains=query) | Q(category__name__icontains=query) | Q(brand__name__icontains=query))
    return render(request, 'search.html', {'bikes': search_results, 'query': query})


@login_required
def profilis(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfilisUpdateForm(request.POST, request.FILES, instance=request.user.profilis)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profilis')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfilisUpdateForm(instance=request.user.profilis)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profilis.html', context)

mysite/bikeshop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-bicycle"
         viewBox="0 0 16 16">
        <path d="M4 4.5a.5.5 0 0 1 .5-.5H6a.5.5 0 0 1 0 1v.5h4.14l.386-1.158A.5.5 0 0 1 11 4h1a.5.5 0 0 1 0 1h-.64l-.311.935.807 1.29a3 3 0 1 1-.848.53l-.508-.812-2.076 3.322A.5.5 0 0 1 8 10.5H5.959a3 3 0 1 1-1.815-3.274L5 5.856V5h-.5a.5.5 0 0 1-.5-.5zm1.5 2.443-.508.814c.5.444.85 1.054.967 1.743h1.139L5.5 6.943zM8 9.057 9.598 6.5H6.402L8 9.057zM4.937 9.5a1.997 1.997 0 0 0-.487-.877l-.548.877h1.035zM3.603 8.092A2 2 0 1 0 4.937 10.5H3a.5.5 0 0 1-.424-.765l1.027-1.643zm7.947.53a2 2 0 1 0 .848-.53l1.026 1.643a.5.5 0 1 1-.848.53L11.55 8.623z"/>
    </svg>
    BIKE SHOP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li>
                <form action="{% url 'search' %}" method="get" class="form-inline my-2 my-md-0">
                    <input name="query" class="form-control" type="text" placeholder="Search">
                </form>
            </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'bike_list' %}">Bikes</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'category_list' %}">Bikes Categories</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'brand_list' %}"> Bikes Brands</a></li>
        </ul>

        <ul class="navbar-nav ms-auto">

            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                     class="bi bi-person-workspace" viewBox="0 0 16 16">
                    <path d="M4 16s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H4Zm4-5.95a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"/>
                    <path d="M2 1a2 2 0 0 0-2 2v9.5A1.5 1.5 0 0 0 1.5 14h.653a5.373 5.373 0 0 1 1.066-2H1V3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v9h-2.219c.554.654.89 1.373 1.066 2h.653a1.5 1.5 0 0 0 1.5-1.5V3a2 2 0 0 0-2-2H2Z"/>
                </svg>
                {{ user.get_username }}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'order_list' %}">Orders</a></li>

            <li class="nav-item"><a class="nav-link" href="{% url 'order_create' %}"> New Order</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}">Log out</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Log in</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Register</a></li>
            {% endif %}

        </ul>
    </div>
</nav>


<div class="col-sm-8 ">{% block content %}{% endblock %}</div>

</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>
</html>

mysite/bikeshop/templates/bike_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3">
    <div class="row">
        <div class="col-md-6">
            {% if bike.image %}
            <img class="card-img-top" src="{{ object.image.url }}" alt="{{ object.name }}">
            {% else %}
            <img class="card-img-top" src="{% static 'images/image.png' %}" alt="{{ object.name }}">
            {% endif %}

        </div>
        <div class="col-md-6">
            <h2>{{ object.name }}</h2>
            <h4>Brand: {{ object.brand.name }}</h4>
            <h4>Category: {{ object.category.name }}</h4>
            <p class="mt-3">{{ object.description }}</p>
            <h4 class="mt-3">Price: ${{ object.price }}</h4>
            {% if user.is_authenticated %}
            {% if object.quantity_available > 0 %}
            <form action="{}" method="post">
                {% csrf_token %}
                <div class="form-group mt-3">
                    <label for="quantity">Quantity:</label>
                    <input type="number" id="quantity" name="quantity" min="1" max="{{ object.quantity_available }}"
                           value="1" class="form-control" required>
                </div>
                <button type="submit" class="btn btn-primary btn-block mt-3">Add to Cart</button>
            </form>
            {% else %}
            <p class="mt-3 text-danger">Out of Stock</p>
            {% endif %}
            {% endif %}
        </div>
    </div>

</div>
{% endblock %}

mysite/bikeshop/templates/bike_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h1>Bikes</h1>

<div class="row">
    {% for bike in object_list %}
    <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            {% if bike.image %}
            <img class="card-img-top" src="{{ bike.image.url }}" alt="{{ bike.name }}">
            {% else %}
            <img class="card-img-top" src="{% static 'images/image.png' %}" alt="{{ bike.name }}">
            {% endif %}
            <div class="card-body">
                <h3 class="card-title">{{ bike.name }}</h3>
                <p class="card-text">{{ bike.description }}</p>
                <p class="card-text">{{ bike.brand.name }} - {{ bike.category.name }}</p>
                <p class="card-text">{{ bike.price }} €</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="{% url 'bike_detail' bike.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                    </div>
                    <small class="text-muted">{{ bike.created_at|date:"F j, Y" }}</small>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
    <p>No bikes available.</p>
    {% endfor %}
</div>


<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">&laquo; First</a></li>
        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
        <li class="page-item disabled"><a class="page-link" href="#">Last &raquo;</a></li>
        {% endif %}
    </ul>
</nav>



{% endblock %}

mysite/bikeshop/templates/brand_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-6">

        {% if brand.image %}
        <img class="card-img-top" src="{{ object.image.url }}" alt="{{ object.name }}">
        {% else %}
        <img class="card-img-top" src="{% static 'images/image.png' %}" alt="{{ object.name }}">
        {% endif %}


    </div>
    <div class="col-lg-6">
        <h1>{{ object.name }}</h1>
        <p>{{ object.description }}</p>
    </div>
</div>

<hr>

<h2>Bikes by {{ object.name }}</h2>

{% if object.bike_set.exists %}
<div class="row">
    {% for bike in object.bike_set.all %}
    <div class="col-lg-4 mb-4">
        <div class="card">


            {% if bike.image %}
            <img class="card-img-top" src="{{ bike.image.url }}" alt="{{ bike.name }}">
            {% else %}
            <img class="card-img-top" src="{% static 'images/image.png' %}" alt="{{ bike.name }}">
            {% endif %}


            <div class="card-body">
                <h4 class="card-title">{{ bike.name }}</h4>
                <p class="mt-3">{{ bike.description }}</p>
                <p class="card-text">Bike category: {{ bike.category.name }}</p>
                <p class="card-text">{{ bike.price }} €</p>
                <a href="{% url 'bike_detail' bike.id %}" class="btn btn-sm btn-outline-secondary">View</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No bikes available by {{ object.name }}.</p>
    {% endif %}
    {% endblock %}

mysite/bikeshop/templates/brand_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    {% for brand in object_list %}
    <div class="col-md-4 mb-4">
        <div class="card">

            {% if brand.image %}
            <img class="card-img-top" src="{{ brand.image.url }}" alt="{{ brand.name }}">
            {% else %}
            <img class="card-img-top" src="{% static 'images/image.png' %}" alt="{{ brand.name }}">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title">{{ brand.name }}</h5>
                <p class="card-text">{{ brand.description }}</p>
                <a href="{% url 'brand_detail' brand.id %}" class="btn btn-primary">View Brand</a>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="col-md-12">
        <p>No brands found.</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

mysite/bikeshop/templates/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-6">

        {% if category.image %}
        <img class="card-img-top" src="{{ object.image.url }}" alt="{{ object.name }}">
        {% else %}
        <img class="card-img-top" src="{% static 'images/image.png' %}" alt="{{ object.name }}">
        {% endif %}


    </div>
    <div class="col-lg-6">
        <h1>{{ object.name }}</h1>
        <p>{{ object.description }}</p>
    </div>
</div>

<hr>

<h2>Bikes by {{ object.name }}</h2>

{% if object.bike_set.exists %}
<div class="row">
    {% for bike in object.bike_set.all %}
    <div class="col-lg-4 mb-4">
        <div class="card">


            {% if bike.image %}
            <img class="card-img-top" src="{{ bike.image.url }}" alt="{{ bike.name }}">
            {% else %}
            <img class="card-img-top" src="{% static 'images/image.png' %}" alt="{{ bike.name }}">
            {% endif %}


            <div class="card-body">
                <h4 class="card-title">{{ bike.name }}</h4>
                <p class="mt-3">{{ bike.description }}</p>
                <p class="card-text">{{ bike.price }} €</p>
                <a href="{% url 'bike_detail' bike.id %}" class="btn btn-sm btn-outline-secondary">View</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<p>No bikes available by {{ object.name }}.</p>
{% endif %}

{% endblock %}

mysite/bikeshop/templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1>Categories</h1>
    <div class="row">
        {% for category in object_list %}
        <div class="col-md-4 mb-3">
            <div class="card">


                {% if category.image %}
                <img class="card-img-top" src="{{ category.image.url }}" alt="{{ category.name }}">
                {% else %}
                <img class="card-img-top" src="{% static 'images/image.png' %}" alt="{{ category.name }}">
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{ category.name }}</h5>
                    <p class="card-text">{{ category.description }}</p>
                    <a href="{% url 'category_detail' category.pk %}" class="btn btn-primary">View Category</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mysite/bikeshop/templates/order_create.html
{% extends 'base.html' %}

{% block content %}
<h1>Create Order</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
{% endblock %}

mysite/bikeshop/templates/order_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Order</h1>

<p>Are you sure you want to delete the order "{{ object }}"?</p>

<form action="" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'order_list' %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

mysite/bikeshop/templates/order_update.html
{% extends 'base.html' %}

{% block content %}
<h1>Update Order #{{ object.id }}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update</button>
</form>
{% endblock %}